/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    HdBreadcrumb: typeof import('./../src/components/hd/Breadcrumb.vue')['default']
    HdButton: typeof import('./../src/components/hd/Button.vue')['default']
    HdInput: typeof import('./../src/components/hd/Input.vue')['default']
    HdNotification: typeof import('./../src/components/hd/Notification.vue')['default']
    IconBytedance: typeof import('@icon-park/vue-next')['Bytedance']
    IconCloseSmall: typeof import('@icon-park/vue-next')['CloseSmall']
    IconDown: typeof import('@icon-park/vue-next')['Down']
    IconFullScreen: typeof import('@icon-park/vue-next')['FullScreen']
    IconHome: typeof import('@icon-park/vue-next')['Home']
    IconIndentLeft: typeof import('@icon-park/vue-next')['IndentLeft']
    IconIndentRight: typeof import('@icon-park/vue-next')['IndentRight']
    IconLog: typeof import('@icon-park/vue-next')['Log']
    IconLogout: typeof import('@icon-park/vue-next')['Logout']
    IconOffScreen: typeof import('@icon-park/vue-next')['OffScreen']
    IconReject: typeof import('@icon-park/vue-next')['Reject']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
